# Generated by Django 5.0.1 on 2024-04-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testre", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Loginmodel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
            ],
        ),
    ]
